[package]
name = "math"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.19.0", default-features = false }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "math"           # The name of the target.
path = "src/lib.rs"    # The source file of the target.
crate-type = ["cdylib"]   # The crate types to generate.

[dependencies]
